### PR TITLE
fix: add conditional claim all on withdraw

### LINKED ISSUE #2548: Unable to withdraw funds from staking (after release period)
**Problem**
When trying to withdraw the funds from a validator (stacking) I'm unable to go on with the tx (there's no error feedback)

**Expected Behavior**
I should be able to withdraw my funds after the the pending release period

**Steps to reproduce**

1. Go to the [Near Wallet stacking](https://wallet.near.org/staking/) page
2. Select a validator to which you've previously clicked `Unstake` and waited the 4 epoch period
3. Click `Withdraw`
4. Nothing happens... No visual feedback

```json
{
  "block_height": 62126595,
  "error": "wasm execution failed with error: FunctionCallError(MethodResolveError(MethodNotFound))",
  "logs": []
}
```

### PR DESCRIPTION
**Pull request by esaminu**
Only claim all tokens on withdrawal if the validator is a staking farm validator.

Closes #2548

### CODE REVIEW

File: packages/frontend/src/components/staking/components/Validator.js [hunk 1]
```diff
@@ -98,25 +98,28 @@ export default function Validator({
...
-                limit: 300,
-            }).then((res) => 
-                Promise.all([
-                    (res || [])
-                    .filter(({balance}) => !new BN(balance).isZero())
-                    .map(({token_id}) => dispatch(claimFarmRewards(validator.accountId, token_id)))
-                ])
-            );
+            if (isFarmingValidator) {
+                await StakingFarmContracts.getFarmListWithUnclaimedRewards({
```
Comment (MaximusHaximus) [inline packages/frontend/src/components/staking/components/Validator.js:106]: Not a blocker for this, but we should fix this up in a follow-up -- since `claim()` takes `token_id` as an argument, we only need to call this once per `token_id` that _any_ farm on the contract yields.

**Review by MaximusHaximus — APPROVED** [review]
:+1: thanks for the speedy fix @esaminu  :)

File: packages/frontend/src/components/staking/components/Validator.js (hunk 1 above)
Comment (esaminu) [reply packages/frontend/src/components/staking/components/Validator.js:106]: Added to WAL-213

**Comment by zcstarr** [comment]
haven't tested this yet on the prod side but 🎉  thanks all for speedy response!
